language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN> -r konnectors/cozy-konnector-pajemploi
    - secure: "lAEvzHkS/x+Om/GgvOJCHMdphPZyP6cTEUCjKnE6Kw3yPqW1IaF0AkJBkgP8H7X5hls1rWIRQSm5YT75Fu8XBxzDWsV/K+qBXmR5yldjMauSaQO64NswWszCPKbIjWHfo6QtXWxZ4KAgxdDGrrfprV+zmcbQj651otfMkZpMDRzQ9RNmpI1fedZ/m+a9ZCjhQ5dSoKEAC8D+9Ui1APmt46gZ9hVQQUtQBNbu+iL0ziuhWD8mqYcOGAzbDTHfxfoMFeri/9h3/BBqUlvukOGn9M2eGCEpQ9YFUC+Fpi1qVCpiD128yWTEyHgXZSAPMxZN4IXojvgVgcD0Q7dwfQPm8Idk9kQqqPXvyI/6scyK+d37sn0fJz/f9pKGfDeKw5rFPaACIyh2ykN14dYn4WGQpMxIVNWK/tBjx/+eOgoV5Xus0iFtVpCybQqYQvZqLJHEJAwCeN0vSE2gOdD3mfYGSrIl5SQeu2mP6pSUTdJ2nVWHDwP+7+cRKZm31cruTWgotFTuA4wu6rFyJxGS9hxnsfTP6c0oiabBi8LDNp9/rLpY4S/mJ9i0RTvlg0lc2N36WouJ/6kBdfjaQbYi6QTvshXsh18gktevOXvM7BQIHWgf4zxpIgM72En+dADiV7TCb5nWhvp4K0FaRKMUct7FZI4weOqEJ1phvIdEVi4scMU="
    # REGISTRY_TOKEN
    - secure: TX5mIMnEJrJO7rKaURVdkTZVfBvtopDjp1zkztSE2JSEDjrSxNjacuGKjb2WTfXijraFDazqGjhSy1mZLQYEF4mHFRcKGGdDBMwgc45VBni6zq6Z70JeYaEiAn5lvbcdLo8LC+mY13Pk/X0TRqNlzVObCRrz3+H/J8x3WF1DVsOC1pMLRJZXxoieRXl9mgzk10nHC6VaqP05PmZS9t4/nUMlR+xUxLfHIasYW/UGgYqVLm/ua8B9vLSy/3dyrDPm7KmCvWZI5JlI4lcaLH9IhTCGDm74/gvauqwBxtSxm8caOLylBAZ427B1cA75uGAIGN0aoOl/apTEt+/fi+7QQEpa/+X6fYaojOfDC1HmcuUWXviGMg1L2bZBMs26rgxymFFaUB+I+BgXCJPXOQkIfMcqETD3pET/32QsTwC4L3iTqWc3RFEvrdQNi/9jy2O3w5h7dp4UmUH7zClS53jUAPipl27Q6I6M1lNXd5U1f7w0F17HQAo6MOvAZm02y9mic8FxxTDmAJL+95sx75D7HVCHHTpAgOUm5tYGeWSjBARvQ6yN7XYQHqPpFMpukf4kmpoTfYVY/AvYMU4yETaCEzXYzfrnMe5MClZCE/OWY+NNbOOhM3q0D1bLOyYik0xPCtCfIHe2eBudaxMTfKjgThHoxckGsyYn1syL9Z1ycIU=
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-pajemploi
    skip-cleanup: true
    script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-pajemploi
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest && yarn deploy && yarn cozyPublish
    on:
      branch: prod
