language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN>
    - secure: "SiRthJV/gKNV6c6eT71uLT5rMaoYELM/N67Ip/wPTeeWdh9xtgTg5HpAas9Zo7F5R32OTrzSjzVJ+7dVa5D+LOQG2FmM8vs5hHXAaWpopRYepd+jaWJZnsKqz+WhWTzOcdiftoiM7McujDxkAAAn0H6/FbXPDD1wwVPiJYS5umTYSFqvabpM+5w+1MWKhlt3FDJ2uSO87f3ahcZT977nH1V4KnAiNnbH34YatOy1yseeCalvfSfTGJuL0zP0REc6ts6aWuij+UuhLEcOU3ewWDe2tedwsA2cG9xX7FLZ94ZunjWlHEb/Wg4CrLHitaZkelaTmGdFSZuvB5RdSrKz5lrrOduWHXRGmoklUw4NnTAu1/0thb8RPUY+bLA2PEgAZEnAVGVWov2hLHYRLI488OyAmgomKxPVyGD37sZK9Igk+tCsEYdcF6VsRgB3vj0N8wJsYCfEcG3s1YJSASupzS/h/7p3XGXy7VYV6b3Vd6Ri5RDAaYeT0KLnP945x+fnq3eb5kw2oNfNHZ54Ja16uEJ4KLadoCtwe/RUWQOEJN0B2DpGlcmFp4i6ZZTvVPaxCCitIDjjtTUqUqEmWdHFpHgdtuSexpIgsuIdJhsXUCwNMCXpUOIyc4fdBf4rEPIsv8A6CxOkgW2uONpc6VgIOnorDPixma0b2DGtk2t9WsM="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-pajemploi
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-pajemploi
    skip-cleanup: true
    script: yarn deploy:prod
    on:
      branch: prod
